#!/usr/bin/env bash
# GENERATED by scripts/bundle.sh from install.sh.in and components/ -- do not edit by hand.
# install.sh — per-host setup for agent-sandbox.
#
# install.sh is GENERATED from install.sh.in and components/ by scripts/bundle.sh
# so it stays a single self-contained file. Edit the template and the components,
# then run scripts/bundle.sh; CI checks that the committed install.sh is current.
#
# Idempotent: safe to run multiple times. Skips steps that are already
# done; only invokes sudo for the few system-level steps (AppArmor
# profile, CA trust) that require it.
#
# Usage:
#   ./install.sh              from a checkout
#   curl -fsSL <raw url of install.sh> | bash
#                             standalone: clones the repository into
#                             ~/.local/share/agent-sandbox/src first
#   ./install.sh --dry-run    no sudo, no systemctl, no environment creation;
#                             everything else runs against $HOME (CI uses this
#                             with a throwaway HOME)
#
# Installs mitmproxy >= 12 into a private environment (venv, else conda), and
# embeds the canonical mitmproxy addon, starter allowlist, and systemd
# user unit so nothing else needs to be carried across hosts. The
# allowlist is only written if it doesn't already exist (so re-runs
# preserve your customizations).

set -euo pipefail

DRY_RUN=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    -h | --help)
      sed -n '/^# Usage:/,/^$/p' "${BASH_SOURCE[0]:-$0}" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "install.sh: unknown argument '$arg' (try --help)" >&2
      exit 2
      ;;
  esac
done

# ----- locations -----
# When run from a checkout, install from it; when run standalone (curl | bash),
# section 1 clones the repository under $STATE_DIR and installs from there.
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]:-$0}")" &>/dev/null && pwd)"
REPO_URL="${AGENT_SANDBOX_REPO:-https://github.com/pearu/agent-sandbox.git}"
CONFIG_DIR="$HOME/.config/agent-sandbox"
SYSTEMD_DIR="$HOME/.config/systemd/user"
BIN_DIR="$HOME/.local/bin"
STATE_DIR="${AGENT_SANDBOX_HOME:-$HOME/.local/share/agent-sandbox}" # proxy runtime lives here

# ----- pretty output -----
if [[ -t 1 ]] && command -v tput >/dev/null; then
  C_BOLD=$(tput bold) C_DIM=$(tput dim) C_RED=$(tput setaf 1)
  C_GREEN=$(tput setaf 2) C_YELLOW=$(tput setaf 3) C_BLUE=$(tput setaf 4)
  C_RESET=$(tput sgr0)
else
  C_BOLD="" C_DIM="" C_RED="" C_GREEN="" C_YELLOW="" C_BLUE="" C_RESET=""
fi
section() { printf '\n%s==> %s%s\n' "$C_BOLD$C_BLUE" "$*" "$C_RESET"; }
ok() { printf '    %s[ok]%s %s\n' "$C_GREEN" "$C_RESET" "$*"; }
warn() { printf '    %s[warn]%s %s\n' "$C_YELLOW" "$C_RESET" "$*"; }
err() {
  printf '    %s[err]%s %s\n' "$C_RED" "$C_RESET" "$*" >&2
  exit 1
}
info() { printf '    %s%s%s\n' "$C_DIM" "$*" "$C_RESET"; }
# System-changing commands (sudo, systemctl) go through here so --dry-run can
# report them instead of running them.
run_sys() {
  if ((DRY_RUN)); then info "(dry-run) would run: $*"; else "$@"; fi
}

# ----- profiles -----
# Everything agent-specific lives in profiles/<name>.sh (see the contract in
# profiles/claude.sh). The installer loads a profile the way the engine does,
# in a subshell, to ask it for its command name, allowlist seed and binary.
profile_query() { # $1 = profile file, $2.. = variable names to print, one per line
  local f=$1
  shift
  (
    # The contract the engine provides to a profile; only the sourced file uses it.
    # shellcheck disable=SC2034,SC2329
    _as_msg() { :; }
    # shellcheck disable=SC2034
    AGENT_SANDBOX_ENGINE=$ENGINE AGENT_SANDBOX_PROFILE_DIR=$SCRIPT_DIR/profiles
    AGENT_SANDBOX_PROFILE=$(basename -- "${f%.sh}")
    # shellcheck disable=SC2034
    profile_command=$AGENT_SANDBOX_PROFILE profile_allowlist_seed=""
    # shellcheck disable=SC1090
    source "$f"
    for v in "$@"; do printf '%s\n' "${!v}"; done
  )
}
profile_probe_bin() { # $1 = profile file; prints "ok <version> <path>" or "missing <reason>"
  local f=$1
  (
    # shellcheck disable=SC2034,SC2329
    _as_msg() { printf '%s\n' "$*" >&2; }
    # shellcheck disable=SC2034
    AGENT_SANDBOX_ENGINE=$ENGINE AGENT_SANDBOX_PROFILE_DIR=$SCRIPT_DIR/profiles
    AGENT_SANDBOX_PROFILE=$(basename -- "${f%.sh}")
    # shellcheck disable=SC2034
    profile_command=$AGENT_SANDBOX_PROFILE profile_bin="" profile_version=""
    # shellcheck disable=SC1090
    source "$f"
    # Run discovery in this shell (not a $(...) subshell) so its results are visible.
    reason_file=$(mktemp)
    if profile_bin_discover 2>"$reason_file"; then
      printf 'ok %s %s\n' "$profile_version" "$profile_bin"
    else
      printf 'missing %s\n' "$(tr '\n' ' ' <"$reason_file")"
    fi
    rm -f "$reason_file"
  )
}

# ----- 1. sanity: find (or fetch) the engine and the profiles -----
section "Sanity check"
((DRY_RUN)) && info "dry run: nothing privileged, no systemctl, no environment creation"
if [[ ! -f "$SCRIPT_DIR/agent-sandbox" ]]; then
  command -v git >/dev/null || err "standalone run needs git to clone $REPO_URL"
  SRC="$STATE_DIR/src"
  if [[ -d "$SRC/.git" ]]; then
    info "updating $SRC"
    git -C "$SRC" pull -q --ff-only
  else
    info "cloning $REPO_URL into $SRC"
    mkdir -p "$STATE_DIR"
    git clone -q "$REPO_URL" "$SRC"
  fi
  SCRIPT_DIR="$SRC"
fi
ENGINE="$SCRIPT_DIR/agent-sandbox"
[[ -f "$ENGINE" ]] || err "agent-sandbox engine not found at $ENGINE"
shopt -s nullglob
profiles=("$SCRIPT_DIR"/profiles/*.sh)
shopt -u nullglob
((${#profiles[@]} > 0)) || err "no profiles found under $SCRIPT_DIR/profiles/"
ok "engine: $ENGINE"
ok "profiles: $(for f in "${profiles[@]}"; do basename -- "${f%.sh}"; done | tr '\n' ' ')"

# ----- 2. packages -----
section "Packages"
missing=()
command -v bwrap >/dev/null || missing+=(bubblewrap)
command -v curl >/dev/null || missing+=(curl)
if ((${#missing[@]} > 0)); then
  if ((DRY_RUN)); then
    warn "(dry-run) missing packages a real run needs: ${missing[*]} (sudo apt install ${missing[*]})"
  else
    err "Missing required packages: ${missing[*]}. Run: sudo apt install ${missing[*]}"
  fi
fi
if command -v bwrap >/dev/null; then
  ok "bwrap installed:    $(bwrap --version 2>/dev/null || echo unknown)"
fi
if command -v slirp4netns >/dev/null; then
  ok "slirp4netns installed (enables AGENT_SANDBOX_NET=strict in the future)"
else
  info "slirp4netns not installed; only needed for the (currently non-functional) strict mode"
fi

# ----- 3. the agents themselves, one per profile -----
section "Agent binaries"
for f in "${profiles[@]}"; do
  name=$(basename -- "${f%.sh}")
  probe=$(profile_probe_bin "$f")
  case "$probe" in
    ok\ *)
      read -r _ ver bin <<<"$probe"
      ok "$name: version $ver at $bin"
      ;;
    *)
      warn "$name: not installed yet (${probe#missing })"
      info "Install it, then re-run; the sandbox launcher is set up regardless."
      ;;
  esac
done

# ----- 4. AppArmor profiles (Ubuntu 24.04+) -----
section "AppArmor profiles for bwrap (and slirp4netns)"
# On kernels that restrict unprivileged user namespaces, each binary that
# needs one gets a profile granting just that. The profile text comes on stdin.
apparmor_profile() {
  local name=$1 target="/etc/apparmor.d/$1"
  if [[ -f "$target" ]]; then
    ok "$target already present"
  elif ((DRY_RUN)); then
    cat >/dev/null
    info "(dry-run) would install $target and load it with apparmor_parser"
  else
    info "Installing AppArmor profile for $name (requires sudo)"
    sudo tee "$target" >/dev/null
    sudo apparmor_parser -r "$target"
    ok "AppArmor profile for $name installed and loaded"
  fi
}
restrict_flag=/proc/sys/kernel/apparmor_restrict_unprivileged_userns
if [[ -e "$restrict_flag" ]] && [[ "$(cat "$restrict_flag")" == "1" ]]; then
  apparmor_profile bwrap <<'AA_BWRAP_EOF'
abi <abi/4.0>,
include <tunables/global>

profile bwrap /usr/bin/bwrap flags=(unconfined) {
  userns,
  include if exists <local/bwrap>
}
AA_BWRAP_EOF
  if command -v slirp4netns >/dev/null; then
    apparmor_profile slirp4netns <<'AA_SLIRP_EOF'
abi <abi/4.0>,
include <tunables/global>

profile slirp4netns /usr/bin/slirp4netns flags=(unconfined) {
  userns,
  include if exists <local/slirp4netns>
}
AA_SLIRP_EOF
  fi
else
  ok "kernel does not restrict unprivileged userns; no profiles needed"
fi

# ----- 5. the egress proxy: mitmproxy >= 12 in its own environment -----
# Distro packages are too old (Ubuntu 24.04 ships 8.1.1, whose certificates
# Python >= 3.13 rejects), so mitmproxy goes into a private environment under
# $STATE_DIR: a Python venv when python3 >= 3.12 with venv is available, else
# a conda/mamba env. An existing environment of either kind is reused.
section "Egress proxy (mitmproxy)"
MITMPROXY_SPEC='mitmproxy>=12,<13'
PROXY_VENV="$STATE_DIR/proxy-venv"
PROXY_CONDA="$STATE_DIR/proxy-env"
python_has_venv() {
  command -v python3 >/dev/null \
    && python3 -c 'import sys, venv, ensurepip; sys.exit(0 if sys.version_info >= (3, 12) else 1)' 2>/dev/null
}
conda_cmd() { command -v mamba || command -v conda || true; }
mkdir -p "$STATE_DIR"
if [[ -x "$PROXY_VENV/bin/mitmdump" ]]; then
  MITMDUMP="$PROXY_VENV/bin/mitmdump"
  ok "reusing $PROXY_VENV"
elif [[ -x "$PROXY_CONDA/bin/mitmdump" ]]; then
  MITMDUMP="$PROXY_CONDA/bin/mitmdump"
  ok "reusing $PROXY_CONDA"
elif ((DRY_RUN)); then
  MITMDUMP="$PROXY_VENV/bin/mitmdump"
  info "(dry-run) would create $PROXY_VENV (or a conda env) and install '$MITMPROXY_SPEC'"
elif python_has_venv; then
  info "Creating $PROXY_VENV and installing '$MITMPROXY_SPEC' with pip (about a minute)"
  python3 -m venv "$PROXY_VENV"
  "$PROXY_VENV/bin/pip" install -q --disable-pip-version-check "$MITMPROXY_SPEC"
  MITMDUMP="$PROXY_VENV/bin/mitmdump"
  ok "installed into $PROXY_VENV"
elif [[ -n "$(conda_cmd)" ]]; then
  info "No python3 >= 3.12 with venv; creating $PROXY_CONDA with $(basename -- "$(conda_cmd)") (about a minute)"
  "$(conda_cmd)" create -y -q -p "$PROXY_CONDA" -c conda-forge "$MITMPROXY_SPEC" >/dev/null
  MITMDUMP="$PROXY_CONDA/bin/mitmdump"
  ok "installed into $PROXY_CONDA"
else
  err "mitmproxy needs python3 >= 3.12 with venv (Debian/Ubuntu: sudo apt install python3-venv) or conda/mamba on PATH"
fi
if [[ -x "$MITMDUMP" ]]; then
  proxy_version=$("$MITMDUMP" --version 2>/dev/null | awk '/^Mitmproxy:/ {print $2}')
  [[ "${proxy_version%%.*}" -ge 12 ]] 2>/dev/null || err "$MITMDUMP reports version '${proxy_version:-?}'; need mitmproxy >= 12"
  ok "mitmdump $proxy_version at $MITMDUMP"
fi
if command -v mitmdump >/dev/null && [[ "$(command -v mitmdump)" != "$MITMDUMP" ]]; then
  info "another mitmdump on PATH, $(command -v mitmdump) ($(mitmdump --version 2>/dev/null | awk '/^Mitmproxy:/ {print $2}')), is not the one the proxy runs"
fi

# ----- 6. mitmproxy CA: generated on the host, trusted only inside sandboxes -----
# The engine binds (system bundle + this CA) over the system bundle's path in
# every sandbox, so nothing on the host has to trust it and no root is needed.
section "mitmproxy CA"
PROXY_CA="$HOME/.mitmproxy/mitmproxy-ca-cert.pem"
if [[ -f "$PROXY_CA" ]]; then
  ok "CA present: $PROXY_CA"
elif ((DRY_RUN)); then
  info "(dry-run) would start mitmdump once to generate $PROXY_CA"
else
  info "Generating the CA (one-time): starting mitmdump briefly"
  "$MITMDUMP" --listen-port 0 >/dev/null 2>&1 &
  _mp_pid=$!
  for _ in 1 2 3 4 5 6 7 8 9 10; do
    sleep 0.5
    [[ -f "$PROXY_CA" ]] && break
  done
  kill "$_mp_pid" 2>/dev/null
  wait "$_mp_pid" 2>/dev/null || true
  [[ -f "$PROXY_CA" ]] || err "mitmdump did not create $PROXY_CA"
  ok "CA generated: $PROXY_CA"
fi
info "trusted inside sandboxes only; the host's trust store is not touched"
if [[ -f /usr/local/share/ca-certificates/mitmproxy.crt ]]; then
  warn "an earlier install trusted this CA system-wide, which is no longer needed. To undo:"
  info "  sudo rm /usr/local/share/ca-certificates/mitmproxy.crt && sudo update-ca-certificates --fresh"
fi

# ----- 7. config files -----
section "Config files"
# Migrate the pre-rename config dir if present (keeps your allowlist edits).
if [[ -d "$HOME/.config/claude-sandbox" && ! -e "$CONFIG_DIR" ]]; then
  mv "$HOME/.config/claude-sandbox" "$CONFIG_DIR"
  ok "migrated ~/.config/claude-sandbox -> $CONFIG_DIR"
fi
mkdir -p "$CONFIG_DIR" "$SYSTEMD_DIR"

# 7a. allowlist_addon.py (static content; safe to overwrite on every run)
cat >"$CONFIG_DIR/allowlist_addon.py" <<'ADDON_EOF'
"""
mitmproxy addon for agent-sandbox — host allowlist enforcement.

Reads ~/.config/agent-sandbox/allowlist.txt on every request and lets
through only hosts that match. Lines are exact hostnames; a leading dot
(".github.com") makes the line match the host AND its subdomains.

Per-session additions (`agent-sandbox --allow HOST`) are read from
<session base>/session.*/allow.txt, where <session base> is
$AGENT_SANDBOX_SESSION_BASE, else $XDG_RUNTIME_DIR/agent-sandbox.<uid>,
else /tmp/agent-sandbox.<uid> -- the same rule the engine uses. A session's
allow.txt is honoured only while the process stamped in its owner.id
("<pid> <start-time>") is alive, so a session that dies without cleaning up
cannot leave a host open, and a recycled PID is never mistaken for the
owner. Note the proxy is shared: while a session lives, its --allow hosts
are reachable from every concurrent session.

Blocked requests return HTTP 403 and are logged to
~/.config/agent-sandbox/blocked.log (one line per attempt) so you can
review what the agent tried to reach and decide whether to add it.

No restart needed when editing the allowlist; the file is re-read on
each request.

HTTPS is refused at the CONNECT stage for hosts not in the allowlist, so a
blocked host never sees a connection from this machine (mitmproxy would
otherwise open a TCP+TLS connection to it, to mirror its certificate, before
the inner request could be checked). The client sees "CONNECT tunnel
failed, response 403"; blocked.log records the host with method CONNECT.
Requests inside an allowed tunnel are still checked per request, so paths
are logged and a Host header naming another host is refused.

Response bodies are streamed to the client as they arrive instead of being
buffered to completion (mitmproxy's default), and the systemd unit runs
mitmdump with http2=false. Together these take downloads and streaming LLM
replies from ~1 MB/s with the first byte at the very end to near-native
speed. Nothing here inspects response bodies, so streaming costs nothing;
every allowlist decision is made before a body flows.
"""

from __future__ import annotations

import datetime
import logging
import os
from pathlib import Path

from mitmproxy import http


CONFIG_DIR = Path.home() / ".config" / "agent-sandbox"
ALLOWLIST_PATH = CONFIG_DIR / "allowlist.txt"
BLOCKED_LOG_PATH = CONFIG_DIR / "blocked.log"

logger = logging.getLogger(__name__)


def _session_base() -> Path:
    override = os.environ.get("AGENT_SANDBOX_SESSION_BASE")
    if override:
        return Path(override)
    runtime = Path(os.environ.get("XDG_RUNTIME_DIR") or f"/run/user/{os.getuid()}")
    if not runtime.is_dir():
        runtime = Path("/tmp")
    return runtime / f"agent-sandbox.{os.getuid()}"


SESSION_BASE = _session_base()


def _owner_alive(owner_file: Path) -> bool:
    """True iff the process stamped in owner.id ("<pid> <start-time>") still runs.

    The start-time (field 22 of /proc/<pid>/stat) is compared too, so a
    recycled PID is never mistaken for the original owner.
    """
    try:
        pid, start = owner_file.read_text().split()[:2]
        stat = Path(f"/proc/{int(pid)}/stat").read_text()
    except (OSError, ValueError):
        return False
    fields = stat.rsplit(")", 1)[1].split()  # fields after "(comm)"; [0] is field 3
    return len(fields) > 19 and fields[19] == start


def _session_lines() -> list[str]:
    """Allowlist lines contributed by live sessions' --allow files."""
    lines: list[str] = []
    if not SESSION_BASE.is_dir():
        return lines
    for session in sorted(SESSION_BASE.glob("session.*")):
        allow, owner = session / "allow.txt", session / "owner.id"
        try:
            if allow.is_file() and owner.is_file() and _owner_alive(owner):
                lines.extend(allow.read_text().splitlines())
        except OSError:
            continue
    return lines


def _parse(lines: list[str], exact: set[str], suffix: list[str]) -> None:
    """Add allowlist lines to (exact_hosts, suffix_patterns).

    A line "github.com" matches only "github.com".
    A line ".github.com" matches "github.com" and "*.github.com".
    """
    for raw in lines:
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        if line.startswith("."):
            exact.add(line[1:])
            suffix.append(line)
        else:
            exact.add(line)


def _load_allowlist() -> tuple[set[str], list[str]]:
    exact: set[str] = set()
    suffix: list[str] = []
    if ALLOWLIST_PATH.exists():
        _parse(ALLOWLIST_PATH.read_text().splitlines(), exact, suffix)
    _parse(_session_lines(), exact, suffix)
    return exact, suffix


def _is_allowed(host: str, exact: set[str], suffix: list[str]) -> bool:
    if host in exact:
        return True
    return any(host.endswith(s) for s in suffix)


def _log_blocked(host: str, method: str, path: str) -> None:
    BLOCKED_LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    ts = datetime.datetime.now().isoformat(timespec="seconds")
    with BLOCKED_LOG_PATH.open("a") as fh:
        fh.write(f"{ts}\t{host}\t{method}\t{path}\n")


def request(flow: http.HTTPFlow) -> None:
    host = flow.request.pretty_host
    exact, suffix = _load_allowlist()
    if _is_allowed(host, exact, suffix):
        return
    _log_blocked(host, flow.request.method, flow.request.path)
    flow.response = http.Response.make(
        403,
        (
            f"agent-sandbox: host {host!r} is not in the allowlist.\n"
            f"To allow it, add a line to {ALLOWLIST_PATH}:\n"
            f"    {host}        (exact)\n"
            f"    .{host}       (and all subdomains)\n"
            f"or relaunch with:  --allow {host}   (this session only)\n"
        ).encode(),
        {"Content-Type": "text/plain; charset=utf-8"},
    )


def http_connect(flow: http.HTTPFlow) -> None:
    """Refuse CONNECT to a non-allowed host before any upstream connection."""
    host = flow.request.host
    exact, suffix = _load_allowlist()
    if _is_allowed(host, exact, suffix):
        return
    _log_blocked(host, "CONNECT", "-")
    flow.response = http.Response.make(
        403,
        f"agent-sandbox: host {host!r} is not in the allowlist.\n".encode(),
        {"Content-Type": "text/plain; charset=utf-8"},
    )


def responseheaders(flow: http.HTTPFlow) -> None:
    flow.response.stream = True
ADDON_EOF
ok "wrote $CONFIG_DIR/allowlist_addon.py"

# 7b. allowlist.txt: the generic starter is written only if absent (re-runs keep
# your edits); then every profile's seed hosts are appended if missing.
if [[ -f "$CONFIG_DIR/allowlist.txt" ]]; then
  ok "$CONFIG_DIR/allowlist.txt already exists (kept as-is)"
else
  cat >"$CONFIG_DIR/allowlist.txt" <<'ALLOW_EOF'
# agent-sandbox allowlist
#
# One hostname per line. Lines starting with "#" are comments.
# A leading dot (".github.com") matches the host AND its subdomains.
# Edits take effect immediately — no restart needed.
#
# Blocked requests are logged to ~/.config/agent-sandbox/blocked.log;
# tail it (`tail -f ~/.config/agent-sandbox/blocked.log`) to see what
# the agent is trying to reach and add hosts here as needed. Hosts an agent
# profile needs (e.g. api.anthropic.com for claude) are appended by install.sh
# from profiles/<name>.allowlist.

# ---- Git / code hosting ----
github.com
api.github.com
codeload.github.com
objects.githubusercontent.com
raw.githubusercontent.com
.githubusercontent.com

# ---- Python packaging ----
pypi.org
files.pythonhosted.org

# ---- Node packaging ----
registry.npmjs.org

# ---- Conda / mamba ----
conda.anaconda.org
repo.anaconda.com
.conda-forge.org

# ---- Rust ----
crates.io
static.crates.io

# ---- Add more below as you hit 403s ----
ALLOW_EOF
  ok "wrote starter $CONFIG_DIR/allowlist.txt"
fi
seed_allowlist() { # $1 = profile name, $2 = its seed file
  local name=$1 seed=$2 line host added=0
  [[ -r "$seed" ]] || return 0
  while IFS= read -r line || [[ -n "$line" ]]; do
    host=${line%%#*}
    host=${host//[[:space:]]/}
    [[ -z "$host" ]] && continue
    if sed 's/#.*//; s/[[:space:]]//g' "$CONFIG_DIR/allowlist.txt" | grep -qxF -- "$host"; then
      continue
    fi
    ((added == 0)) && printf '\n# ---- %s profile (added by install.sh) ----\n' "$name" >>"$CONFIG_DIR/allowlist.txt"
    printf '%s\n' "$host" >>"$CONFIG_DIR/allowlist.txt"
    added=$((added + 1))
  done <"$seed"
  if ((added > 0)); then ok "allowlist: added $added host(s) for the $name profile"; else ok "allowlist: $name profile hosts already present"; fi
}
for f in "${profiles[@]}"; do
  seed_allowlist "$(basename -- "${f%.sh}")" "$(profile_query "$f" profile_allowlist_seed)"
done

# 7c. systemd user unit (static; safe to overwrite)
cat >"$SYSTEMD_DIR/agent-sandbox-mitmproxy.service" <<'UNIT_EOF'
[Unit]
Description=mitmproxy enforcing allowlist for the agent sandbox
Documentation=file:@ENGINE@
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
# http2=false: mitmproxy's HTTP/2 path is pure Python and an order of magnitude
# slower than HTTP/1.1; with response streaming in the addon this is near-native.
ExecStart=@MITMDUMP@ \
    --listen-host 127.0.0.1 \
    --listen-port 8888 \
    --set block_global=false \
    --set termlog_verbosity=info \
    --set flow_detail=0 \
    --set http2=false \
    -s %h/.config/agent-sandbox/allowlist_addon.py
Restart=on-failure
RestartSec=2s
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=default.target
UNIT_EOF
sed -i -e "s|@ENGINE@|$ENGINE|g" -e "s|@MITMDUMP@|$MITMDUMP|g" "$SYSTEMD_DIR/agent-sandbox-mitmproxy.service"
ok "wrote $SYSTEMD_DIR/agent-sandbox-mitmproxy.service"

# ----- 8. systemd: reload, enable, start -----
section "Systemd user service"
# Migrate off the pre-rename unit if present: it also binds 127.0.0.1:8888, so
# leaving it enabled would collide with agent-sandbox-mitmproxy.service.
legacy=0
[[ -f "$SYSTEMD_DIR/claude-mitmproxy.service" ]] && legacy=1
((DRY_RUN)) || ! systemctl --user is-enabled claude-mitmproxy.service >/dev/null 2>&1 || legacy=1
if ((legacy)); then
  if ((DRY_RUN)); then
    info "(dry-run) would disable and remove the legacy claude-mitmproxy.service"
  else
    systemctl --user disable --now claude-mitmproxy.service >/dev/null 2>&1 || true
    rm -f "$SYSTEMD_DIR/claude-mitmproxy.service"
    ok "migrated off legacy claude-mitmproxy.service"
  fi
fi
run_sys systemctl --user daemon-reload
if ((DRY_RUN)); then
  info "(dry-run) would enable and (re)start agent-sandbox-mitmproxy.service"
else
  systemctl --user enable agent-sandbox-mitmproxy.service >/dev/null 2>&1 || true
  systemctl --user restart agent-sandbox-mitmproxy.service
  sleep 1
  if systemctl --user is-active --quiet agent-sandbox-mitmproxy.service; then
    ok "agent-sandbox-mitmproxy.service is active"
  else
    warn "agent-sandbox-mitmproxy.service did not start; inspect: journalctl --user -u agent-sandbox-mitmproxy"
  fi
fi

# ----- 9. PATH symlinks: one per profile command -> the engine -----
section "PATH symlinks (\$HOME/.local/bin/<agent> -> agent-sandbox)"
mkdir -p "$BIN_DIR"
commands=()
for f in "${profiles[@]}"; do
  cmd=$(profile_query "$f" profile_command)
  commands+=("$cmd")
  link="$BIN_DIR/$cmd"
  if [[ -L "$link" && "$(readlink -f "$link")" == "$ENGINE" ]]; then
    ok "$link already points at the engine"
  elif [[ -L "$link" && "$(basename -- "$(readlink -f "$link" || readlink "$link")")" == claude.sh ]]; then
    ln -sfn "$ENGINE" "$link"
    ok "re-pointed $link from the legacy claude.sh wrapper -> $ENGINE"
  elif [[ -L "$link" && ! -e "$link" ]]; then
    ln -sfn "$ENGINE" "$link"
    ok "replaced dangling symlink $link -> $ENGINE"
  elif [[ -e "$link" ]]; then
    warn "$link exists and is not the expected symlink (left untouched)"
    info "If it is the agent's own binary you no longer want on PATH, remove it and re-run."
  else
    ln -s "$ENGINE" "$link"
    ok "symlinked $link -> $ENGINE"
  fi
done

# Verify $HOME/.local/bin precedes any other copy of each command on PATH; the
# engine infers the profile from the symlink name.
for cmd in "${commands[@]}"; do
  if command -v "$cmd" >/dev/null; then
    resolved=$(readlink -f "$(command -v "$cmd")")
    if [[ "$resolved" == "$ENGINE" ]]; then
      ok "\`$cmd\` on PATH resolves to the agent-sandbox engine"
    else
      warn "\`$cmd\` on PATH resolves to $resolved (not the engine)"
      info "Ensure $BIN_DIR comes before other $cmd installations in PATH."
    fi
  fi
done

# ----- 10. smoke test -----
section "Smoke tests"
if bwrap --ro-bind / / --unshare-user --unshare-pid -- /bin/true 2>/dev/null; then
  ok "bwrap can create user+pid namespaces"
else
  warn "bwrap user-namespace test failed — see the agent-sandbox header for AppArmor notes"
fi
# Verifies the contract of the default `proxy` net mode: HTTPS_PROXY-honouring
# clients reach allowlisted hosts and ONLY those. Both halves matter -- a proxy
# that answers but does not refuse is not enforcing anything. (Other net modes
# make different promises: `strict` additionally blocks raw sockets and would
# get its own check when it lands; `open` filters nothing; `none` has no
# network. The user picks the mode per launch and owns its residual risk.)
# api.anthropic.com answers 401 for /v1/models without a key, proving the
# request reached Anthropic through the proxy; example.com is not in the
# starter allowlist, so it must be refused at CONNECT (curl gets no response,
# code 000). A non-000 code for example.com means the allowlist is not
# enforcing.
proxy_get() { # $1 = url; echoes the HTTP code (000 = refused/failed)
  curl -sS --cacert "$PROXY_CA" --proxy http://127.0.0.1:8888 --max-time 15 \
    -o /dev/null -w '%{http_code}' "$1" 2>/dev/null || true
}
if ((DRY_RUN)); then
  info "(dry-run) proxy request skipped"
else
  case "$(proxy_get https://api.anthropic.com/v1/models)" in
    200 | 401)
      ok "proxy reaches an allowlisted host (api.anthropic.com)"
      # The other half of the contract: a non-allowlisted host is refused.
      block_code=$(proxy_get https://example.com/)
      if [[ "$block_code" == 000 ]]; then
        ok "proxy refuses a non-allowlisted host (example.com blocked at CONNECT)"
      else
        warn "SECURITY: non-allowlisted example.com returned HTTP $block_code through the proxy — the allowlist is NOT enforcing; check $CONFIG_DIR/allowlist_addon.py is loaded"
      fi
      ;;
    000) warn "no answer through the proxy; check 'systemctl --user status agent-sandbox-mitmproxy' and that api.anthropic.com is in $CONFIG_DIR/allowlist.txt" ;;
    *) warn "unexpected response from api.anthropic.com via the proxy" ;;
  esac
fi

# ----- 11. summary -----
section "Done"
cat <<SUMMARY
Next steps:
  - Open a fresh shell (or \`hash -r\`) so the new command(s) are on PATH: ${commands[*]}
  - cd into a project and run one of them.
  - Tail blocked requests:  tail -f $CONFIG_DIR/blocked.log
  - Edit the allowlist:     \$EDITOR $CONFIG_DIR/allowlist.txt
  - Bypass proxy one-shot:  AGENT_SANDBOX_NET=open ${commands[0]}
SUMMARY
