#!/usr/bin/env bash
# Regenerate install.sh from install.sh.in and components/.
#
#   @@GENERATED@@              -> a "do not edit" banner
#   @@INCLUDE components/x@@   -> the file's content, verbatim (it sits inside
#                                a quoted heredoc in the template)
#
# Run from anywhere; CI runs it and fails if `git diff --exit-code install.sh`
# then shows a difference.
set -euo pipefail
cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.."
out=install.sh
tmp="$(mktemp "$out.XXXXXX")"
while IFS= read -r line || [[ -n "$line" ]]; do
  if [[ "$line" == "@@GENERATED@@" ]]; then
    printf '# GENERATED by scripts/bundle.sh from install.sh.in and components/ -- do not edit by hand.\n'
  elif [[ "$line" =~ ^@@INCLUDE\ ([^@]+)@@$ ]]; then
    cat -- "${BASH_REMATCH[1]}"
  else
    printf '%s\n' "$line"
  fi
done <install.sh.in >"$tmp"
chmod 755 "$tmp"
mv -f -- "$tmp" "$out"
echo "bundled $out from install.sh.in + $(grep -c '^@@INCLUDE' install.sh.in) components"
